# Generated by Django 3.1.14 on 2025-04-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_pokemonentity_realtion_pokemons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='realtion_pokemons',
            new_name='relation_pokemons',
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(null=True),
        ),
    ]
