# Generated by Django 3.1.14 on 2025-04-06 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20250406_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='relation_pokemons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon'),
        ),
    ]
